name: mobile
description: Premium Instagram Public Video Downloader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  provider: any
  dio: any
  path_provider: any
  gal: ^2.3.0
  shared_preferences: any
  intl: any
  gap: any
  uuid: any
  fluttertoast: any
  
  google_fonts: ^6.1.0
  open_file: ^3.3.2
  flutter_animate: any
  shimmer: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
